server:
  port: 8080

spring:
  datasource:
    url: DATABASE_URL
    username: DB_USERNAME
    password: DB_PASSWORD
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:/schema-postgresql.sql
      platform: postgres


  
