server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dpg-d4loko8gjchc73arjllg-a.oregon-postgres.render.com:5432/projeto_banco_studioa
    username: admin
    password: ZdLclBl6zIrvftzhY4oM29CW0oJ1kE2d
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:/schema-postgresql.sql
      platform: postgres


  
